print ("Nama : Dhewan Agum Mahendra")
print ("NIM : 04119007")
print ("Prodi : Sistem Komputer")
print ("Kampus : Universitas Narottama")
print ("======================")
print ("APLIKASI TOKENISASI")
print ("======================")
print ("Masukan Kalimat :")
k = input()
print(k.split())
for kata in k.split():
  print(kata)
print ("     ")  
print("Terdeksi Ada {} kata".format(len(k.split())))
